Initial commit
Initial implementation of `has`, a script to check existence of any
given command, if any of the given commands do not exists the command
will exit with an error code 1. Has command takes an arbitrary amount of
commands to check.

USAGE
	has <command> [<command> ...]

OPTIONS
	-h --help	Show help

EXAMPLES
	Check for a command that does not exist
	has jq
	error: cannot find command "jq"

	Check for multiple commands where some commands do not exist
	has cat ls echo git jq
	error: cannot find command "git" "jq"

	Check for multiple commands that do exist
	has cat ls echo